[package]
name = "run-onnx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log="0.4"
dotenv = "0.15"
env_logger="0.10"
wonnx = "0.4"
pollster = "0.3"
image = "0.24"
ndarray = "0.15"